{
  "format_version": 1,
  "sksl": {
    "entrypoint": "nebula_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_hash(vec2 p)\n{\n    return fract(sin(dot(p, vec2(127.09999847412109375, 311.70001220703125))) * 43758.546875);\n}\n\nfloat FLT_flutter_local_noise(vec2 p)\n{\n    vec2 i = floor(p);\n    vec2 f = fract(p);\n    f = (f * f) * (vec2(3.0) - (f * 2.0));\n    vec2 param = i;\n    float a = FLT_flutter_local_hash(param);\n    vec2 param_1 = i + vec2(1.0, 0.0);\n    float b = FLT_flutter_local_hash(param_1);\n    vec2 param_2 = i + vec2(0.0, 1.0);\n    float c = FLT_flutter_local_hash(param_2);\n    vec2 param_3 = i + vec2(1.0);\n    float d = FLT_flutter_local_hash(param_3);\n    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 p_1 = (uv * 4.0) + vec2(uTime * 0.0500000007450580596923828125, uTime * 0.02999999932944774627685546875);\n    vec2 param_4 = p_1;\n    vec2 param_5 = p_1 * 2.0;\n    vec2 param_6 = p_1 * 4.0;\n    float n = ((FLT_flutter_local_noise(param_4) * 0.5) + (FLT_flutter_local_noise(param_5) * 0.25)) + (FLT_flutter_local_noise(param_6) * 0.125);\n    vec3 col1 = vec3(0.0, 0.5299999713897705078125, 1.0);\n    vec3 col2 = vec3(0.37999999523162841796875, 0.119999997317790985107421875, 0.540000021457672119140625);\n    vec3 col3 = vec3(0.0, 0.0500000007450580596923828125, 0.12999999523162841796875);\n    vec3 color = mix(col3, mix(col1, col2, vec3(n)), vec3(n * 0.60000002384185791015625));\n    float alpha = n * 0.4000000059604644775390625;\n    fragColor = vec4(color, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}