{
  "format_version": 1,
  "sksl": {
    "entrypoint": "stars_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform float uDensity;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_hash(vec2 p)\n{\n    return fract(sin(dot(p, vec2(127.09999847412109375, 311.70001220703125))) * 43758.546875);\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 grid = floor(uv * 200.0);\n    vec2 local = fract(uv * 200.0);\n    vec2 param = grid;\n    float h = FLT_flutter_local_hash(param);\n    float starBrightness = step(0.9700000286102294921875, h);\n    float twinkle = 0.699999988079071044921875 + (0.300000011920928955078125 * sin((uTime * 3.0) + (h * 100.0)));\n    float dist = length(local - vec2(0.5));\n    float star = (starBrightness * smoothstep(0.300000011920928955078125, 0.0, dist)) * twinkle;\n    vec3 color = mix(vec3(0.800000011920928955078125, 0.89999997615814208984375, 1.0), vec3(1.0, 0.89999997615814208984375, 0.699999988079071044921875), vec3(h));\n    fragColor = vec4(color * star, star);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uDensity",
        "rows": 1,
        "type": 10
      }
    ]
  }
}