{
  "format_version": 1,
  "sksl": {
    "entrypoint": "warp_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform float uIntensity;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 center = vec2(0.5);\n    vec2 dir = uv - center;\n    float dist = length(dir);\n    float speed = uTime * 2.0;\n    float streak = pow(max(0.0, 1.0 - (dist * 2.0)), 3.0);\n    float warp = streak * uIntensity;\n    float angle = atan(dir.y, dir.x);\n    float lines = (abs(sin((angle * 8.0) + (speed * 0.5))) * 0.5) + 0.5;\n    vec3 warpColor = mix(vec3(0.0, 0.5299999713897705078125, 1.0), vec3(1.0), vec3(warp * lines));\n    float alpha = (warp * lines) * 0.800000011920928955078125;\n    fragColor = vec4(warpColor, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uIntensity",
        "rows": 1,
        "type": 10
      }
    ]
  }
}